skinparam {
  RoundCorner 4
  Shadowing false
}
skinparam Default {
  FontColor #505050
  FontSize 14
}
skinparam Header {
  FontColor #D7A72D
  FontSize 10
}
skinparam Footer {
  FontColor #999999
  FontSize 10
}
skinparam Title {
  FontSize 16
}

skinparam Actor {
  BackgroundColor #eeeeee
  BorderColor #505050
}
skinparam Arrow {
  Color #000000
}
skinparam Box {
  Padding 10
}
skinparam Participant {
  BackgroundColor #FFFFFF
  BorderColor #333333
  Padding 10
}
skinparam Note {
  BackgroundColor #7f8c8d
  BorderColor #7f8c8d
  FontStyle bold
  FontColor #ffffff
}

skinparam Activity {
  ArrowColor #000000
  BackgroundColor #eeeeee
  BorderColor #999999
  StartColor #000000
  EndColor #000000
  BarColor #000000

  DiamondBackgroundColor #eeeeee
  DiamondBorderColor #999999
}
skinparam Sequence {
  ArrowThickness 2
  BoxBackgroundColor #DDDDDD
  BoxBorderColor #999999
  LifeLineBorderColor #000000
  ReferenceBorderColor #000000
}
