name: Generate PlantUML images
on:
  push:
    branches:
      - develop
      - feature/**
    tags-ignore:
      - '*'

jobs:
  diagrams:
    name: Generate PlantUML images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: unshallow
      - name: Git config
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git config --local core.quotepath false
      - name: Extract the targets
        run: echo ::set-output name=list::$(git diff --stat --name-only $(git log --committer="github-actions" -1 --pretty=%h) $(git rev-parse --short HEAD) | grep -e .iuml -e .puml | xargs echo | awk '{if($0 ~ ".iuml"){print "**/*.puml"}else{print $0}}')
        id: changed_files
      - name: Process diagrams
        uses: Timmy/plantuml-action@5f5f57e
        env:
          TZ: Asia/Tokyo
        with:
          args: '-svg ${{ steps.changed_files.outputs.list }}'
        if: steps.changed_files.outputs.list
      - name: Commit files
        run: |
          git add .
          git commit -m 'Automatically generated PlantUML images.'
          git push
        if: steps.changed_files.outputs.list
