name: Draw diagrams
on: push

jobs:
  diagrams:
    name: Draw diagrams
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Process diagrams
        uses: Timmy/plantuml-action@v1
        with:
          args: '-tutxt *.pu'
      - name: Display diagrams
        run: cat *.utxt
