name: Generate PlantUML images
on:
  push:
    branches:
      - develop
      - feature/**
    tags-ignore:
      - '*'

jobs:
  diagrams:
    name: Generate PlantUML images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: unshallow
      - name: Git rev-parse
        run: |
          echo `git rev-parse --short HEAD`
          echo ${{  github.sha  }}
          echo ${{  github.event  }}
          echo ${{  github.event_path  }}
          echo ${{  github.workflow  }}
          echo ${{  github.run_id  }}
          echo ${{  github.run_number  }}
          echo ${{  github.actor  }}
          echo ${{  github.repository  }}
          echo ${{  github.event_name  }}
          echo ${{  github.ref  }}
          echo ${{  github.workspace  }}
          echo ${{  github.action  }}
          echo `git log --committer="github-actions" -1 --pretty=%h`
          echo `git log --author="github-actions" -1 --pretty=%h`
          echo `git rev-parse --short HEAD`
          echo `git diff --stat --name-only $(git log --committer="github-actions" -1 --pretty=%h) $(git rev-parse --short HEAD)`
      - name: Process diagrams
        uses: Timmy/plantuml-action@5f5f57e
        with:
          args: '-svg *.puml'
      - name: Commit files
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m 'Automatically generated PlantUML images.'
          git push || ture
