name: generate PlantUML images
on: push

jobs:
  diagrams:
    name: generate PlantUML images
    runs-on: ubuntu-latest
    steps:
      - name: check out repository
        uses: actions/checkout@v2
      - name: process diagrams
        uses: Timmy/plantuml-action@v1
        with:
          args: '-svg activity-diagram.puml'
      - name: commit files
        run: |
          git config --global user.email "workflow@example.com"
          git config --global user.name "workflow user"
          git add .
          git commit -m 'generate PlantUML images.'
