name: Generate PlantUML images
on:
  push:
    branches:
      - develop
      - feature/**
    tags-ignore:
      - '*'

jobs:
  diagrams:
    name: Generate PlantUML images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: unshallow
      - name: Enable Japanese
        run: |
          sudo localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
          LANG=ja_JP.UTF-8
          LANGAGE=ja_JP.ja
          LC_ALL=ja_JP.UTF-8
          export LANG
          export LANGAGE
          export LC_ALL
          locale -a
      - name: Extract the targets
        run: |
          echo ::set-output name=list::$(git diff --stat --name-only $(git log --committer="github-actions" -1 --pretty=%h) $(git rev-parse --short HEAD) | grep -e .iuml -e .puml | xargs echo | awk '{if($0 ~ ".iuml"){print "**/*.puml"}else{print $0}}')
          echo $(git diff --stat --name-only $(git log --committer="github-actions" -1 --pretty=%h) $(git rev-parse --short HEAD) | grep -e .iuml -e .puml | xargs echo | awk '{if($0 ~ ".iuml"){print "**/*.puml"}else{print $0}}')
        id: changed_files
        env: 
          LANG: ja_JP.UTF-8
          LANGAGE: ja_JP.ja
          LC_ALL: ja_JP.UTF-8
      - name: Process diagrams
        uses: Timmy/plantuml-action@5f5f57e
        env:
          TZ: Asia/Tokyo
          LANG: ja_JP.UTF-8
          LANGAGE: ja_JP.ja
          LC_ALL: ja_JP.UTF-8
        with:
          args: '-svg ${{ steps.changed_files.outputs.list }}'
        if: steps.changed_files.outputs.list
      - name: Commit files
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m 'Automatically generated PlantUML images.'
          git push
        if: steps.changed_files.outputs.list
